server.port=${SERVER_PORT:8081}

spring.application.name=processing-app
spring.jackson.property-naming-strategy=SNAKE_CASE

hipsum.base-url=${HIPSUM_BASE_URL:https://hipsum.co}
hipsum.max-concurrency=${HIPSUM_MAX_CONCURRENCY:8}
hipsum.type=${HIPSUM_TYPE:hipster-centric}
